apps/contacts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "contacts"

urlpatterns = [

    path("contacts-list/", views.list_contacts, name="list"),
    path("contacts-create/", login_required(views.ContactCreateView.as_view()), name="create"),
    path("contacts-update/<int:pk>/", login_required(views.ContactUpdateView.as_view()), name="update"),
    path("contacts-delete/<int:pk>/", login_required(views.ContactDeleteView.as_view()), name="delete"),
    path("contacts-details/<int:pk>/", views.ContactDetailView.as_view(), name="details"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('generate/', include('apps.first_example.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path("user/", include("apps.users.urls")),
    path('sessions-example/', include('apps.sessions_example.urls')),
    path("logs/", include("apps.middleware_counter.urls")),
    path('', include('apps.first_example.urls_root')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contacts/models.py
from django.db import models


class Country(models.Model):

    name = models.CharField(max_length=50)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.name}"

    __repr__ = __str__


class Contact(models.Model):
    name = models.CharField(max_length=50)
    phone = models.PositiveSmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    is_auto_generated = models.BooleanField(default=False)

    avatar = models.ImageField(
        max_length=255,
        upload_to="contacts/contact/avatar/",
        blank=True,
        null=True,
    )

    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
        related_name="contacts",
        default=None,
        null=True,
        blank=True
    )

    def __str__(self) -> str:
        return f"{self.name} - {self.phone}"

    __repr__ = __str__

apps/contacts/views.py
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.urls import reverse_lazy
from apps.contacts.models import Contact


def list_contacts(request):
    return render(
        request=request,
        template_name="contacts/contacts_list.html",
        context={
            "contacts": Contact.objects.all(),
        },
    )


class ContactCreateView(CreateView):
    model = Contact
    fields = (
        "name",
        "phone",
        "avatar",
        "country",
    )
    success_url = reverse_lazy("contacts:list")


class ContactUpdateView(UpdateView):
    model = Contact
    fields = (
        "id",
        "name",
        "phone",
        "avatar",
        "country",
    )
    success_url = reverse_lazy("contacts:list")


class ContactDeleteView(DeleteView):
    model = Contact
    success_url = reverse_lazy("contacts:list")


class ContactDetailView(DetailView):
    model = Contact
    pk_url_kwarg = "pk"

apps/templates/contacts/contact_confirm_delete.html
{% extends '_helpers/_base.html' %}

{%  block title %}Delete contact {%  endblock  %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <p>Are you sure you want to delete "{{ object }}"?</p>

        <button type="submit" class="btn btn-warning">Confirm</button>
    </form>
{% endblock %}

apps/templates/contacts/contact_detail.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>{{ object.headline }}</h1>
    <p>{{ object.content }}</p>
    <p>ID contact: {{ object.id }}</p>
    <p>Name contact: {{ object.name }}</p>
    <p>Phone number: {{ object.phone }}</p>
    <p>Contact created at: {{ object.created_at }}</p>
    <p>Contact modified at: {{ object.modified_at }}</p>
{% endblock %}

apps/templates/contacts/contact_form.html
{% extends "_helpers/_base.html" %}
{%  block title %} Contact edit {%  endblock  %}
{% load crispy_forms_tags %}

{%  block content %}

   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
   </form>
{% endblock %}}

apps/templates/contacts/contacts_list.html
{% extends '_helpers/_base.html' %}

{%  block title %}
    Contact list
{%  endblock  %}

{%  block content %}
    <a href="{% url "contacts:create" %}">
        <button class="btn btn-success">
            Create new contact
        </button>
    </a>

    <ol>
        {% for contact in contacts %}
            <li class="row my-elements-box">
            <div class="col my-element-style">
             <div class="contact-avatar">
                        {% if contact.avatar %}
                            <img src="{{ contact.avatar.url }}" alt="Avatar" class="my-avatar" >
                        {% endif %}
                    </div>
                <div class="my-element-content">
                 {{ contact.name }}
                <span> - </span>
                Phone number: {{ contact.phone }}
                <span> - </span>
                Modified info: {{ contact.modified_at }}
                <span> - </span>
                {%  if contact.country is not None %}
                    Country info: {{ contact.country }}
                {% else %}
                    Country info: Unknown
                {% endif %}
                </div>
            </div>
            </li>

            <div class="my-element-controls">
             <a href="{% url "contacts:update" pk=contact.id %}">
                    <button class="btn btn-warning">
                        Edit
                    </button>
                </a>
                <a href="{% url "contacts:delete" pk=contact.id %}">
                    <button class="btn btn-danger">
                        Delete
                    </button>
                </a>
                <a href="{% url "contacts:details" pk=contact.id %}">
                    <button class="btn btn-info">
                        More details
                    </button>
                </a>
             </div>
        {% endfor %}
    </ol>
{% endblock %}