apps/contacts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "contacts"

urlpatterns = [

    path("contacts-list/", views.list_contacts, name="list"),
    path("contacts-create/", login_required(views.ContactCreateView.as_view()), name="create"),
    path("contacts-update/<int:pk>/", login_required(views.ContactUpdateView.as_view()), name="update"),
    path("contacts-delete/<int:pk>/", login_required(views.ContactDeleteView.as_view()), name="delete"),
    path("contacts-details/<int:pk>/", views.ContactDetailView.as_view(), name="details"),
]

apps/first_example/urls.py
from django.urls import path
from apps.first_example import views
from django.urls import include

app_name = "first_example"

urlpatterns = [
    path(
        "users/",
        include(
            [
                path("", views.UsersView.as_view(), name="users"),
                path("<int:amount>", views.UsersView.as_view(), name="users"),
            ]
        ),
    ),
]

apps/sessions_example/urls.py
from django.urls import path
from . import views

app_name = "sessions_example"

urlpatterns = [

    path("", views.SessionUserView.as_view(), name="index"),
]

apps/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = "user"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("update_u/<int:pk>/", login_required(views.UserUpdateView.as_view()), name="update_u"),
    path("logout", views.logout_request, name="logout"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('generate/', include('apps.first_example.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path("user/", include("apps.users.urls")),
    path('sessions-example/', include('apps.sessions_example.urls')),
    path("logs/", include("apps.middleware_counter.urls")),
    path('', include('apps.first_example.urls_root')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/models.py

# Create your models here.

apps/base/views.py

# Create your views here.

apps/templates/_helpers/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>

    {# [connect_bootstrap]-[BEGIN] #}
    <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
    >
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
    ></script>
    {# [connect_bootstrap]-[END] #}

<link
href = "{% static "styles/index.css" %}"
rel = "stylesheet"
>
<link rel="icon" type="image/svg+xml" href="{% static "favicon/favicon.svg" %}">

</head>
<body>
<div class="container-fluid">
    {% include '_helpers/_header.html' %}

    {% block content %}
        Hello!
    {% endblock %}
</div>
</body>
</html>

apps/templates/_helpers/_header.html
{% load static %}

<header>
    <p class="navbar navbar-expand-lg navbar-light bg-light">
        <img class="logo" src="{% static "/logo/logo.svg" %}" alt="site-logo" />
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url "root:index" %}">Home</a></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url "first_example:users" amount=5 %}"> Users </a></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url "contacts:list" %}"> Contacts </a></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url "sessions_example:index" %}"> Sessions </a></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url "logger-counter:list" %}"> Logger-counter </a></li>
    </ul>
    </nav>

    <ul>
    {% if user.is_authenticated %}

        <li class="last">
            <p> {{ user.username }} |<a href = "{% url "logout" %}"> Logout </a></p>
            <div class="col my-element-style">
                <div class="user-avatar">
                    {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" alt="Avatar" >
                    {% else %}
                        Add a photo
                    {% endif %}
                </div>
            </div>
            <p><a href="{% url "user:update_u" pk=user.id %}">
                <button class="btn btn-success">
                    Edit account
                </button>
            </a></p>
        </li>


    {% else %}
        <li class="last">
            <a href="{% url "login" %}" > Login </a>| <a href="{% url "user:signup" %}" > Signup users</a>
        </li>
    {% endif %}
    </ul>

</header>