apps/middleware_counter/urls.py
from django.urls import path

from . import views

app_name = "logger-counter"

urlpatterns = [
    path("", views.LogsListView.as_view(), name="list"),
    path("list-users/", views.UserListView.as_view(), name="list_user"),
    path("list-sessions/", views.SessionsListView.as_view(), name="list_sessions"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('generate/', include('apps.first_example.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path("user/", include("apps.users.urls")),
    path('sessions-example/', include('apps.sessions_example.urls')),
    path("logs/", include("apps.middleware_counter.urls")),
    path('', include('apps.first_example.urls_root')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/middleware_counter/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class RequestLog(models.Model):
    path = models.CharField(max_length=300)
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="users",
        null=True,
        blank=False,
    )
    session_id = models.CharField(max_length=100, null=True, default="Unknown session")
    counter = models.SmallIntegerField(max_length=None, null=True, default=0)
    visit_time = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.path} - {self.user}"

    __repr__ = __str__

apps/middleware_counter/views.py
from django.views.generic import ListView, TemplateView

from apps.middleware_counter.models import RequestLog

from django.contrib.sessions.backends.cached_db import SessionStore
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger


class LogsListView(ListView):
    paginate_by = 30
    model = RequestLog
    template_name = "middleware_counter/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = RequestLog.objects.all().order_by("-id")
        paginator = Paginator(context["object_list"], self.paginate_by)

        page = self.request.GET.get("page")

        try:
            context["object_list"] = paginator.page(page)
        except PageNotAnInteger:
            context["object_list"] = paginator.page(1)
        except EmptyPage:
            context["object_list"] = paginator.page(paginator.num_pages)

        count_logs = RequestLog.objects.count()
        context["title"] = "List"
        context["count_logs"] = count_logs
        return context


class SessionsListView(ListView):
    paginate_by = 30
    model = RequestLog
    template_name = "middleware_counter/list_sessions.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        session: SessionStore = self.request.session
        session_id = session.session_key

        context["object_list"] = RequestLog.objects.filter(session_id=session_id).order_by("-id")
        paginator = Paginator(context["object_list"], self.paginate_by)

        page = self.request.GET.get("page")

        try:
            context["object_list"] = paginator.page(page)
        except PageNotAnInteger:
            context["object_list"] = paginator.page(1)
        except EmptyPage:
            context["object_list"] = paginator.page(paginator.num_pages)

        count_logs = RequestLog.objects.filter(session_id=session_id).order_by("-id").count()
        context["title"] = "List"
        context["count_logs"] = count_logs
        return context


class UserListView(TemplateView):
    model = RequestLog
    template_name = "middleware_counter/list_user.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["object_list"] = RequestLog.objects.filter().order_by("-id")
        page = self.request.GET.get("page")

        paginator = Paginator(context["object_list"], 30)

        try:
            context["object_list"] = paginator.page(page)
        except PageNotAnInteger:
            context["object_list"] = paginator.page(1)
        except EmptyPage:
            context["object_list"] = paginator.page(paginator.num_pages)

        count_logs = RequestLog.objects.filter().order_by("-id").count()
        context["title"] = "List"
        context["count_logs"] = count_logs
        return context

apps/templates/middleware_counter/list.html
{% extends "_helpers/_base.html" %}

{%  block title %}

    Logs List
{%  endblock  %}

{% block content %}
    <a href="{% url "logger-counter:list_user" %}">
        <button class="btn btn-primary">
            Log List by User
        </button>
    </a>
    <a href="{% url "logger-counter:list_sessions" %}">
        <button class="btn btn-primary">
            Log List by Sessions
        </button>
    </a>
    <p>Count all Logs: {{ count_logs }}</p>
    <ol>
        {% for log in object_list %}
            <li>
                <div class="col my-element-style">
                    <div class="my-element-content">
                        <p>ID: {{ log.id }}</p>
                        <p>Request path: {{ log.path }}</p>
                        {% if user.is_authenticated %}
                            <p>User: {{ log.user }}</p>
                        {% else %}
                            <p>User: Unknown user</p>
                        {% endif %}
                        <p>Session id: {{ log.session_id }}</p>
                        <p>Count_requests: {{ log.counter }}</p>
                        <p>Created time: {{ log.visit_time }}</p>
                    </div>
                </div>
            </li>
        {% endfor %}

    </ol>
    {%  include "middleware_counter/paginate.html"  %}



{% endblock %}

apps/templates/middleware_counter/list_sessions.html
{% extends "_helpers/_base.html" %}

{%  block title %}

    Sessions List
{%  endblock  %}

{% block content %}


    <p>Count Logs by sessions : {{ count_logs }}</p>
    <ol>

        {% for log in object_list %}
            <li>
                <div class="col my-element-style">
                    <div class="my-element-content">
                        <p>ID: {{ log.name}}</p>
                        <p>Request path: {{ log.path }}</p>
                        {% if user.is_authenticated %}
                            <p>User: {{ log.user }}</p>
                        {% else %}
                            <p>User: Unknown user</p>
                        {% endif %}
                        <p>Session id: {{ log.session_id }}</p>
                        <p>Count_requests: {{ log.counter }}</p>
                        <p>Created time: {{ log.visit_time }}</p>
                    </div>


                </div>
            </li>
        {% endfor %}
    </ol>
    {%  include "middleware_counter/paginate.html" %}

{% endblock %}

apps/templates/middleware_counter/list_user.html
{% extends "_helpers/_base.html" %}

{% block title %}

    Users List
{% endblock %}

{% block content %}


    <p>Count Logs by user : {{ count_logs }}</p>
    <ol>

        {% for log in object_list %}
            <li>
                <div class="col my-element-style">
                    <div class="my-element-content">
                        <p>ID: {{ log.name }}</p>
                        <p>Request path: {{ log.path }}</p>
                        {% if user.is_authenticated %}
                            <p>User: {{ log.user }}</p>
                        {% else %}
                            <p>User: Unknown user</p>
                        {% endif %}
                        <p>Session id: {{ log.session_id }}</p>
                        <p>Count_requests: {{ log.counter}}</p>
                        <p>Created time: {{ log.visit_time }}</p>
                    </div>


                </div>
            </li>
        {% endfor %}
    </ol>
    {%  include "middleware_counter/paginate.html"  %}

{% endblock %}

apps/templates/middleware_counter/paginate.html
{% block pagination %}
    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                            Previous
                        </a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="{{ request.path }}?page={{ num }}">{{ num }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ request.path }}?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                            Next
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}